sudo: false # use container-based infrastructure (faster, among other things)
language: ruby
cache: bundler
jdk:
  - openjdk8
rvm:
  - 2.3.3
before_install:
  - gem update --system 2.7.7
  - gem --version
  - gem install s3_website
  - gem install dotenv
script:
  - test $TRAVIS_BRANCH == "master" && s3_website push 
